" default indentation is for python
set shiftwidth=4
set tabstop=4
set expandtab
set autoindent
set smartindent
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2 expandtab

set nowrap
set number
syntax on

" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin('~/.vim/plugged')
	Plug 'pangloss/vim-javascript'
	Plug 'vim-python/python-syntax'
call plug#end()
